name: Terragrunt Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment to destroy (dev, integration, prod)'
        required: true
        default: dev
      queue_exclude_s3:
        description: 'Set to "true" to exclude the components/s3 directory'
        required: true
        default: "true"

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}   # Set the secret as an environment variable
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::922858306127:role/GitHubActionsRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Terraform and Terragrunt
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip
          curl -Lo terraform.zip https://releases.hashicorp.com/terraform/1.11.2/terraform_1.11.2_linux_amd64.zip
          unzip terraform.zip && sudo mv terraform /usr/local/bin/
          curl -Lo terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.76.6/terragrunt_linux_amd64
          chmod +x terragrunt && sudo mv terragrunt /usr/local/bin/

      - name: Destroy Environment
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment }}
          echo "Destroying environment: $ENVIRONMENT"
          cd src/envs/$ENVIRONMENT
          if [ "${{ github.event.inputs.queue_exclude_s3 }}" == "true" ]; then
              EXTRA_ARGS='--queue-exclude-dir "components/s3"'
          else
              EXTRA_ARGS=""
          fi
          eval "yes | terragrunt run-all destroy --non-interactive --parallelism=1 $EXTRA_ARGS"
